-- TODO 테이블
CREATE TABLE "TODO" (
    "TODO_NO"   NUMBER      PRIMARY KEY,
    "TODO_TITLE"   VARCHAR2(100)      NOT NULL,
    "TODO_ST"   CHAR(1) DEFAULT 'N' CHECK ("TODO_ST" IN ('Y','N'))
);

COMMENT ON COLUMN "TODO"."TODO_NO" IS '투두 번호';
COMMENT ON COLUMN "TODO"."TODO_TITLE" IS '투두 내용';
COMMENT ON COLUMN "TODO"."TODO_ST" IS '투두 상태';

CREATE SEQUENCE SEQ_TODO_NO; -- 투두 번호 시퀀스

INSERT INTO TODO VALUES(SEQ_TODO_NO.NEXTVAL, '이마트 장보기', DEFAULT);
INSERT INTO TODO VALUES(SEQ_TODO_NO.NEXTVAL, '리액트 과제하기', DEFAULT);
INSERT INTO TODO VALUES(SEQ_TODO_NO.NEXTVAL, '왕십리 6시 친구만나기', DEFAULT);

SELECT * FROM TODO;

SELECT TODO_NO, TODO_TITLE, TODO_ST
FROM TODO
ORDER BY TODO_NO;
  		
